hayatonanba/quizee

biome.json
package-lock.json
package.json
src/app/globals.css
src/components/atoms/Button/Button.stories.tsx
src/components/atoms/Button/Button.tsx
src/components/atoms/Button/index.ts

https://www.notion.so/1861977f05d980a087b6cb723753d913
close

feat: ボタンを作成

---

src/components/atoms/SwitchButton/SwitchButton.stories.tsx
src/components/atoms/SwitchButton/SwitchButton.tsx
src/components/atoms/SwitchButton/index.ts

スイッチボタンを実装
close 
https://www.notion.so/c1aae2e2b8224e4f804e3a35a0829f50

feat: スイッチを作成

---

src/components/atoms/Button/Button.tsx
src/components/molecules/HomeButtons/HomeButtons.stories.tsx
src/components/molecules/HomeButtons/HomeButtons.tsx
src/components/molecules/HomeButtons/index.ts

2つのホームボタンを作成
close 
https://www.notion.so/18d1977f05d9803baa7ce87fd5881577

feat: ホームボタンの作成

---

src/components/molecules/ChoiceButton/ChoiceButton.stories.tsx
src/components/molecules/ChoiceButton/ChoiceButton.tsx
src/components/molecules/ChoiceButton/index.ts

close 
https://www.notion.so/18d1977f05d980318595dfbf457dc937

feat: 選択肢の作成

---

src/components/organisms/SiteTitle/SiteTitle.stories.tsx
src/components/organisms/SiteTitle/SiteTitle.tsx
src/components/organisms/SiteTitle/index.ts

タイトルのサイズを決定
close 
https://www.notion.so/1861977f05d980e69b01e0e3946cda85

feat: タイトルを作成

---

.storybook/preview.ts
src/components/organisms/MyListHeader/MyListHeader.stories.tsx
src/components/organisms/MyListHeader/MyListHeader.tsx
src/components/organisms/MyListHeader/index.ts

リストのヘッダーを作成
close 
https://www.notion.so/03b1f13592df4094901e940af74a2d05

feat: リストヘッダー作成

---

src/components/molecules/ChoiceInput/ChoiceInput.stories.tsx
src/components/molecules/ChoiceInput/ChoiceInput.tsx
src/components/molecules/ChoiceInput/index.ts

選択肢作成のフィールドを作成
close 
https://www.notion.so/4fb8b8830e36441b8a2c601603320820

feat: 選択肢作成のフィールドを作成

---

src/components/organisms/QuizField/QuizField.stories.tsx
src/components/organisms/QuizField/QuizField.tsx
src/components/organisms/QuizField/index.ts

クイズの問題を表示する部分を作成
close 
https://www.notion.so/18d1977f05d98077abf3cc4747ee0faf

feat: クイズの問題を表示する部分を作成

---

package-lock.json
package.json
src/components/molecules/ChoiceInput/ChoiceInput.stories.tsx
src/components/molecules/ChoiceInput/ChoiceInput.tsx
src/components/organisms/QuizBuilder/QuizBuilder.stories.tsx
src/components/organisms/QuizBuilder/QuizBuilder.tsx
src/components/organisms/QuizBuilder/index.ts
src/lib/schema.ts
src/store/useQuizStore.ts

クイズの作成画面を実装
- 上記の要件に合わせて以前作ったもの修正しました。
close 
https://www.notion.so/9bea3fdfb21d4b09a2e82d735ffa3755

feat: クイズの作成画面を実装

---

src/components/molecules/ChoiceButton/ChoiceButton.tsx
src/components/molecules/ChoiceInput/ChoiceInput.tsx
src/components/organisms/QuizBuilder/QuizBuilder.tsx
src/components/organisms/QuizField/QuizField.tsx
src/components/organisms/StreakBubbleWithIcon/StreakBubbleWithIcon.tsx
src/store/useQuizStore.ts

自分の環境で適切にbiomeが効いていなくてerrorを吐いていたのでまとめて解消。
close

fix: biomeのerrorをまとめて解消

---

package-lock.json
package.json
src/components/atoms/Badge/Badge.tsx
src/components/organisms/QuizCard/QuizCard.stories.tsx
src/components/organisms/QuizCard/QuizCard.tsx
src/components/organisms/QuizCard/index.ts

クイズカードの作成
close 
https://www.notion.so/53bacaf4bee44b318b78a5adce54620e

feat: クイズカードの作成

---

.gitignore
prisma/schema.prisma

feat: dbのスキーマを定義

---

src/lib/prisma/client.ts

chore: prismaのクライアントを用意

---

package-lock.json
package.json
src/app/api/(hono)/[[...route]]/route.ts
src/lib/hono/client.ts
src/server/controllers/quiz/getQuizees.ts
src/server/controllers/quiz/postQuiz.ts
src/server/hono.ts
src/server/models/quizSchema.ts
src/server/routes/quizRoutes.ts

Postメゾットを導入しました。
close 
https://www.notion.so/api-POST-8fca4a881bfd4b15a6b7a8d68e5384eb

feat: apiのpostを導入

---

src/app/(pages)/quiz/new/page.tsx
src/components/organisms/QuizBuilder/QuizBuilder.tsx
src/components/organisms/QuizBuilderHeader/QuizBuildHeader.tsx
src/components/templates/createQuizTemplate.tsx/createQuizTemplate.tsx

feat: クイズ作成画面を実装

---

src/server/controllers/quiz/deleteQuiz.ts
src/server/hono.ts
src/server/models/quizSchema.ts
src/server/routes/quizRoutes.ts

クイズ削除のAPIを実装
close 
https://www.notion.so/api-DELETE-78e0d2f8ca5c4c808c31272c145e3235

feat: 削除機能を実装

---

src/server/controllers/quiz/updateQuiz.ts
src/server/hono.ts
src/server/models/quizSchema.ts
src/server/routes/quizRoutes.ts

クイズの更新APIを実装
close 
https://www.notion.so/api-PUT-a30ce0f89053499aa3f7ca809dd63e36

feat: 更新機能を実装

---

src/server/controllers/quiz/getMyQuizzes.ts
src/server/hono.ts
src/server/models/quizSchema.ts
src/server/routes/quizRoutes.ts

ユーザーの作成したクイズを返すAPI
close 
https://www.notion.so/api-GET-c43e99d11a394f6eaad0453371c5fccf

feat: userの作成クイズを返すapi

---

src/server/controllers/quiz/getQuiz.ts
src/server/hono.ts
src/server/routes/quizRoutes.ts

idから一つのクイズを取得するapi
close 
https://www.notion.so/GET-1951977f05d980cbb40fe8eaf131b013

feat: 一つのクイズを取得するapi

---

src/server/controllers/quiz/getRandomQuiz.ts
src/server/hono.ts
src/server/routes/quizRoutes.ts

ランダムにクイズの問題をー問取得するapiを作成
close

feat: ランダムにクイズの問題をー問取得するapiを作成

---

src/app/(pages)/quiz/[quizId]/edit/page.tsx
src/components/organisms/QuizCard/QuizCard.tsx
src/components/templates/editQuizTemplate/editQuizTemplate.tsx
src/components/templates/myListTemplate/myListTemplate.tsx
src/store/useQuizStore.ts

feat: クイズを更新するページの作成

---

src/server/controllers/quiz/postQuiz.ts
src/server/controllers/quiz/updateQuiz.ts

投稿と編集の際に公開の有無を設定できるように修正
close

fix: 公開非公開の設定を修正

---

next.config.mjs
src/app/(pages)/home/page.tsx
src/components/molecules/HomeButtons/HomeButtons.tsx
src/components/organisms/QuizField/QuizField.stories.tsx
src/components/organisms/QuizField/QuizField.tsx
src/components/organisms/StreakBubbleWithIcon/StreakBubbleWithIcon.tsx

feat: ホームページを実装

---

src/components/organisms/QuizCard/QuizCard.stories.tsx
src/components/organisms/QuizCard/QuizCard.tsx
src/components/templates/myListTemplate/myListTemplate.tsx

fix: リンクが適切にカードの上をラップするように修正

---

src/app/(pages)/quiz/[quizId]/edit/page.tsx
src/components/organisms/QuizBuilder/QuizBuilder.tsx
src/components/templates/createQuizTemplate.tsx/createQuizTemplate.tsx
src/components/templates/editQuizTemplate/editQuizTemplate.tsx
src/lib/schema.ts
src/server/controllers/quiz/updateQuiz.ts
src/server/models/quizSchema.ts
src/store/useQuizStore.ts

fix: 選択肢を新規作成、削除できない問題を解消

---

src/components/organisms/MyListHeader/MyListHeader.tsx

fix: 左右に余白をとる

---

src/components/organisms/StreakBubbleWithIcon/StreakBubbleWithIcon.tsx

- ログアウトボタンを実装
- sp画面での見え方を修正
close

fix: 連続正解の表示UIを修正

---

src/server/controllers/quiz/getCurrentStreak.ts
src/server/hono.ts
src/server/models/quizSchema.ts
src/server/routes/quizRoutes.ts

feat: 連続正解数のapi

---

src/app/(pages)/home/page.tsx
src/components/organisms/QuizField/QuizField.tsx
src/server/controllers/quiz/postCorrect.ts
src/server/hono.ts
src/server/models/quizSchema.ts
src/server/routes/quizRoutes.ts

feat: post-api作成

---

src/app/(pages)/quiz/my-list/page.tsx
src/components/molecules/Pagination/Pagination.tsx
src/server/controllers/quiz/getMyQuizzes.ts

fix: ページネーションを修正

---

src/components/atoms/Button/Button.tsx
src/components/molecules/ChoiceButton/ChoiceButton.tsx

fix: ホームボタンのスタイルを修正

---

src/lib/schema.ts

fix: バリデーションで送信できない問題を解消

---

prisma/migrations/20250303152350_add_is_answering_to_user/migration.sql
prisma/migrations/20250303171540_add_prev_quiz_id_to_user/migration.sql
prisma/schema.prisma
src/components/organisms/QuizField/QuizField.tsx
src/server/controllers/quiz/getRandomQuiz.ts
src/server/controllers/quiz/postCorrect.ts

fix: 多重回答防止と連続して同じ問題が出題されないよう修正

---

src/server/controllers/user/updateUser.ts
src/server/hono.ts
src/server/models/userSchema.ts
src/server/routes/userRoutes.ts

ユーザ名を変更するための処理を追加しました
- src/server/controllers下に新たに/user/updateUser.tsを作成
- src/server/routes下に新たに/userRoutes.tsを作成
- src/server/modelsファイルにUsernameタイプを追加
close 
実際に動くかをまだ試せていない

feat: ユーザ名変更のapiを追加

---

src/components/molecules/SettingButton/SettingButton.stories.tsx
src/components/molecules/SettingButton/SettingButton.tsx
src/components/molecules/SettingButton/index.ts

feat: 設定のナブボタンを作成

---

src/components/organisms/SiteTitle/SiteTitle.tsx
src/components/templates/topPageTemplate/topPageTemplate.tsx

feat: トップページに規約のリンクを設置

---

src/lib/schema.ts
src/server/models/quizSchema.ts

chore: サーバーバリデーションを修正

---

src/app/(pages)/quiz/[quizId]/edit/page.tsx
src/app/(pages)/quiz/my-list/page.tsx
src/app/(pages)/quiz/new/page.tsx
src/app/page.tsx
src/components/molecules/ChoiceButton/ChoiceButton.tsx
src/components/organisms/QuizField/QuizField.tsx
src/components/templates/createQuizTemplate/createQuizTemplate.tsx
src/components/templates/editQuizTemplate/editQuizTemplate.tsx

chore: コードの軽微修正

---

src/app/(pages)/home/page.tsx
src/components/organisms/QuizField/QuizField.stories.tsx
src/components/organisms/QuizField/QuizField.tsx
src/components/templates/homePageTemplate/homePageTemplate.tsx

chore: 作成者の名前を表示しない

---

src/components/organisms/QuizBuilder/QuizBuilder.tsx
src/lib/schema.ts
src/server/models/choiceSchema.ts
src/server/models/quizSchema.ts
src/store/useQuizStore.ts

fix: フォームのバリデーションを解消

---

src/app/(pages)/home/page.tsx
src/app/(pages)/quiz/my-list/page.tsx
src/server/controllers/quiz/deleteQuiz.ts
src/server/controllers/quiz/getMyQuizzes.ts
src/server/controllers/quiz/getQuiz.ts
src/server/controllers/quiz/postCorrect.ts
src/server/controllers/quiz/postQuiz.ts
src/server/controllers/quiz/updateQuiz.ts
src/server/hono.ts

fix: cache周りを大幅に改善

---

src/components/templates/myListTemplate/myListTemplate.tsx
src/server/controllers/quiz/getMyQuizzes.ts
src/server/controllers/quiz/getQuiz.ts
src/server/controllers/quiz/getRandomQuiz.ts
src/server/controllers/quiz/postQuiz.ts
src/server/controllers/quiz/updateQuiz.ts
src/server/models/quizSchema.ts
src/server/models/userSchema.ts

fix: prismaの記述変更

---

.eslintrc.json
package.json
src/components/templates/createQuizTemplate/createQuizTemplate.tsx
src/server/controllers/user/updateUser.ts
src/server/hono.ts
src/server/routes/userRoutes.ts

fix: build errorを修正

---

src/app/(pages)/home/page.tsx
src/app/(pages)/quiz/[quizId]/edit/page.tsx
src/app/(pages)/quiz/my-list/page.tsx

fix: headers部分を修正

---

src/app/(pages)/quiz/[quizId]/edit/page.tsx
src/app/(pages)/quiz/my-list/page.tsx
src/app/(pages)/quiz/new/page.tsx
src/app/page.tsx
src/auth.ts

feat: 未認証時、ページをブロック

---

.eslintrc.json
src/components/atoms/SwitchButton/SwitchButton.stories.tsx
src/components/molecules/ChoiceInput/ChoiceInput.stories.tsx
src/components/organisms/QuizBuilder/QuizBuilder.stories.tsx
src/components/organisms/QuizBuilderHeader/QuizBuildHeader.stories.tsx

fix: storybookのエラーを修正

---

prisma/schema.prisma

feat: dbを移設
